---
language: node_js
node_js:
  - "6"

sudo: true
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm config set spin false
  - npm install --global bower
  - bower install

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a8ac258d6b53dc5935cb
    on_success: always
    on_failure: always
    on_start: always
